### ISSUE TITLE
Domain

### ISSUE THREAD

**Issue by vermont42** [Deco354/SwiftDec#9]
What is the domain for your blog? I'd like to read it! The blog, not the domain. :P

**Comment by Deco354** [comment]
I still need to come up with a good domain name and host it there once I've finished the site.
Master is temporarily hosted [here](https://swifty.netlify.com/). There's only one article on there atm. 

Will probably still be another month until I launch as I'm completely new to web development and still need to play around with things like SASS and Jekyll.

**Comment by vermont42** [comment]
For hosting, I've been happy with AWS and appreciate having that skill in my toolbox.

Please email me the URL when it's ready. vermontcoder at gmail dot com.

Consider adding your blog to Dave Verwer's blog [directory](https://iosdevdirectory.com/contributing/). Being featured is 🎉.

Good post on unit testing. The @twostraws book on that topic is excellent.
